name: Diabetes Prediction App

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
      - 'releases/**'

jobs:
  # Run tests job
  tests:
    runs-on: ubuntu-latest
    steps:
      # Clone repository on the linux machine
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: ./.github/actions/python-setup

      # Run Pytest
      - name: Run Tests
        run: |
          PYTHONPATH=. pytest | tee tests_logs.txt
          exit ${PIPESTATUS[0]}

      # Upload the tests logs as artifacts in a .txt file
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests_logs
          path: tests_logs.txt

  model_pipeline:
    runs-on: ubuntu-latest
    steps:
      # Clone repository on the linux machine
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: ./.github/actions/python-setup

      # Train & evaluate the models
      - name: Train & Evaluate Models
        run: python main.py -train-models -evaluate-models -use-best-params > metrics_logs.txt

      # Upload metrics logs as artifact
      - name: Upload Metrics Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: metrics_logs
          path: metrics_logs.txt

      # Upload metrics as artifacts
      - name: Upload Metrics
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: metrics
          path: evaluation_results.json

  ai_analysis:
    runs-on: ubuntu-latest
    needs: [tests, model_pipeline]
    if: always()

    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Install the Gemini SDK
      - name: Install Gemini SDK
        run: pip install google-genai

      # Download the previously stored evaluation metrics artifact
      - name: Download Evaluation Metrics
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: metrics

      # Download the previously stored metrics logs artifact
      - name: Download Metrics Logs
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: metrics_logs

      # Download the previously stored tests logs artifact
      - name: Download Tests Logs
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: tests_logs

      # Make a call to the Gemini API with the Gemini API key and evaluation metrics
      # in order to obtain the metrics analysis
      - name: Analyze Metrics
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scripts/gemini_analyze_metrics.py > metrics_analysis_result.txt

      # Upload metrics analysis result as artifact
      - name: Upload Metrics Analysis Result
        uses: actions/upload-artifact@v4
        with:
          name: metrics_analysis_result
          path: metrics_analysis_result.txt

      # Make a call to the Gemini API with the Gemini API key and tests logs
      # in order to obtain the tests logs analysis
      - name: Analyze Tests Logs
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scripts/gemini_analyze_tests_logs.py > tests_analysis_result.txt

      # Upload tests analysis result as artifact
      - name: Upload Tests Analysis Result
        uses: actions/upload-artifact@v4
        with:
          name: tests_analysis_result
          path: tests_analysis_result.txt

  ai_summary:
    runs-on: ubuntu-latest
    needs: [ai_analysis]
    if: always()

    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      # Load metrics analysis report
      - name: Load Metrics Analysis
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: metrics_analysis_result

      # Load tests analysis report
      - name: Load Tests Analysis
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: tests_analysis_result

      # Show GitHub step summary with the loaded artifacts
      - name: Show Summary
        run: |
          echo "# AI Analysis Report" >> $GITHUB_STEP_SUMMARY

          echo "## Metrics Analysis" >> $GITHUB_STEP_SUMMARY
          cat metrics_analysis_result.txt >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY

          echo "## Tests Logs Analysis" >> $GITHUB_STEP_SUMMARY
          cat tests_analysis_result.txt >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-latest
    needs: [tests, model_pipeline]

    if: |
      needs.tests.result == 'success' &&
      needs.model_pipeline.result == 'success

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t diabetes-prediction-app

      - name: Save Docker Image
        run: docker save diabetes-prediction-app -o diabetes-prediction-app.tar

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: diabetes-prediction-app.tar