# This workflow is triggered on the code updates
# (when 1- code is pushed, 2 - pull request is (re)-opened, 3 - pull request is updated).
# The workflow only works on main & release branches.

# The workflow:
# 1. Installs Python
# 2. Installs dependencies
# 3. Runs tests

name: Diabetes Prediction App

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
      - 'releases/**'

jobs:
  # Run tests job
  tests:
    runs-on: ubuntu-latest
    steps:
      # Setup Python
      - name: Setup Python
        uses: ./.github/actions/python-setup

      # Run Pytest
      - name: Run tests
        run: PYTHONPATH=. pytest

  model_pipeline:
    runs-on: ubuntu-latest
    steps:
      # Clone repository on the linux machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: ./.github/actions/python-setup

      # Train & evaluate the models
      - name: Train & Evaluate Models
        run: python main.py -train-models -evaluate-models -save-models -use-best-params

      # Upload metrics as artifacts
      - name: Upload Metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: evaluation_results.json

      #### TODO  ####
#      - name: Download Metrics
#        uses: actions/download-artifact@v4
#        with:
#          name: metrics